java_library (
  name = "oio",
  srcs = glob(["*.java"]),
  deps = [
    "//server/src/main/java/de/voidnode/trading4j/server/protocol",
    "//server/src/main/java/de/voidnode/trading4j/server/protocol/exceptions",
    "//server/src/main/java/de/voidnode/trading4j/server/reporting",
  ],
  visibility = [
    "//server/src/main/java/de/voidnode/trading4j/server:__pkg__",
  ]
)