java_library (
  name = "expertadvisorfactory",
  srcs = glob(["*.java"]),
  deps = [
    "//core/src/main/java/de/voidnode/trading4j/api",
    "//core/src/main/java/de/voidnode/trading4j/domain",
    "//core/src/main/java/de/voidnode/trading4j/functionality/broker",
    "//core/src/main/java/de/voidnode/trading4j/functionality/expertadvisor",
  ],
  visibility = ["//visibility:public"]
)