java_library (
  name = "strategyexpertadvisor",
  srcs = glob(["*.java"]),
  deps = [
    "//core/src/main/java/de/voidnode/trading4j/api",
    "//core/src/main/java/de/voidnode/trading4j/domain"
  ],
  visibility = ["//visibility:public"]
)