java_library (
  name = "server",
  srcs = glob(["*.java"]),
  deps = [
    "//core/src/main/java/de/voidnode/trading4j/api",
    "//core/src/main/java/de/voidnode/trading4j/domain",
    "//core/src/main/java/de/voidnode/trading4j/expertadvisorfactory",
    "//core/src/main/java/de/voidnode/trading4j/moneymanagement",
    "//core/src/main/java/de/voidnode/trading4j/moneymanagement/standard",
    "//core/src/main/java/de/voidnode/trading4j/tradetracker" ,
    "//server/src/main/java/de/voidnode/trading4j/server/protocol",
    "//server/src/main/java/de/voidnode/trading4j/server/reporting",
    "//server/src/main/java/de/voidnode/trading4j/server/reporting/implementations",
    "//server/src/main/java/de/voidnode/trading4j/server/oio",
  ],
  visibility = [
    "//visibility:public"
  ]
)