java_library (
  name = "exceptions",
  srcs = glob(["*.java"]),
  deps = [
  ],
  visibility = [
    "//server/src/main/java/de/voidnode/trading4j/server/protocol:__pkg__",
    "//server/src/main/java/de/voidnode/trading4j/server/oio:__pkg__",
    "//server/src/test/java/de/voidnode/trading4j/server/protocol:__pkg__",
    "//server/src/test/java/de/voidnode/trading4j/server/protocol/expertadvisor:__pkg__",
    "//server/src/test/java/de/voidnode/trading4j/server/oio:__pkg__",
  ]
)