java_library (
  name = "assertions",
  srcs = glob(["**/*.java"]),
  deps = [
    "//core/src/main/java/de/voidnode/trading4j/domain",
    "@org_assertj_assertj_core//jar",
  ],
  visibility = [
    "//core/src/test/java:__subpackages__",
    "//server/src/test/java:__subpackages__"
  ]
)
