java_binary(
  name = "examples",
  srcs = glob([
    "src/main/java/**/*.java",
  ]),
  main_class = "de.voidnode.trading4j.examples.ExpertAdvisorServer",
  deps = [
    "//core",
    "//server"
  ]
)
