java_library (
  name = "indicators",
  srcs = glob(["**/*.java"]),
  deps = [
    "//core/src/main/java/de/voidnode/trading4j/api",
    "//core/src/main/java/de/voidnode/trading4j/domain",
    "//core/src/main/java/de/voidnode/trading4j/functionality/smoothers"
  ],
  visibility = ["//visibility:public"]
)