java_library (
  name = "messages",
  srcs = glob(["*.java"]),
  deps = [
    "//core/src/main/java/de/voidnode/trading4j/domain"
  ],
  visibility = [
    "//server/src/main/java/de/voidnode/trading4j/server/protocol:__pkg__",
  ]
)