java_library (
  name = "testutils",
  srcs = glob(["*.java"]),
  deps = [
    "//core/src/main/java/de/voidnode/trading4j/domain",
  ],
  visibility = [
    "//core/src/test/java:__subpackages__",
    "//server/src/test/java:__subpackages__"
  ]
)
